name: 🐞 Bug Fix
description: Submit a pull request to fix a bug
title: "[Fix]: "
labels: ["bugfix"]
  - type: textarea
    id: description
    attributes:
      label: Describe the bug fix
      description: What problem does this PR solve, and how did you fix it?
      placeholder: |
        Fixed issue where `portion new` crashed when path didn't exist.
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Summary of code changes
      description: List the main code or logic changes introduced in this fix.
      placeholder: |
        - Added path existence check in `cli/new_command.py`
        - Updated error message for invalid directories
    validations:
      required: true

  - type: input
    id: issue
    attributes:
      label: Related Issue
      description: Link to the related issue (if applicable)
      placeholder: "#123"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-Submission Checklist
      description: Please confirm the following before submitting:
      options:
        - label: I have tested the fix locally
          required: true
        - label: All validation actions (flake8, mypy, pytest) pass successfully
          required: true
        - label: The bug is clearly reproducible and resolved
          required: true
        - label: Code follows the existing style and conventions
          required: true
