name: 📘 Documentation Update
description: Submit a pull request to improve or clarify documentation
title: "[Docs]: "
labels: ["documentation"]

body:
  - type: textarea
    id: summary
    attributes:
      label: Describe the documentation change
      description: What did you update or improve, and why?
      placeholder: |
        Updated the installation guide to include `poetry install` instructions.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details of the change
      description: List the specific sections or files updated and what changed.
      placeholder: |
        - Updated `README.md` setup section  
        - Fixed typos in `CONTRIBUTING.md`  
        - Clarified usage examples in `docs/usage.md`
    validations:
      required: true
          
  - type: dropdown
    id: change_type
    attributes:
      label: Type of Documentation Change
      description: Select the most appropriate type of change.
      options:
        - Minor (typos, small rewording, or format fix)
        - Moderate (added/updated a section or example)
        - Major (significant rewrite or new documentation page)
      default: 0
    validations:
      required: true

  - type: input
    id: issue
    attributes:
      label: Related Issue (if applicable)
      description: Link to an issue related to this documentation change.
      placeholder: "#123"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-Submission Checklist
      description: Please confirm before submitting:
      options:
        - label: I have verified spelling and formatting
          required: true
        - label: The documentation content is accurate and up to date
          required: true
        - label: All code examples (if any) were tested successfully
          required: false
