name: 💡 Feature Implementation
description: Submit a pull request to add a new feature
title: "[Feature]: "
labels: ["feature"]

body:
  - type: textarea
    id: summary
    attributes:
      label: Describe the feature
      description: What does this feature add or improve?
      placeholder: |
        Added `portion template download` command to fetch project templates.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Implementation details
      description: Explain how the feature is implemented or designed.
      placeholder: |
        - Introduced `TemplateManager` class  
        - Added subcommand handler for `template download`  
        - Updated tests for the new feature
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: Type of Change
      description: Select the level of impact of this feature
      options:
        - Minor (small enhancement, low impact)
        - Moderate (significant addition, medium impact)
        - Major (core feature or big change)
      default: 0
    validations:
      required: true

  - type: input
    id: issue
    attributes:
      label: Related Issue (if applicable)
      description: Link to the issue or discussion this PR addresses
      placeholder: "#123"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-Submission Checklist
      description: Please confirm the following before submitting:
      options:
        - label: Code follows project style and conventions
          required: true
        - label: Feature tested locally
          required: true
        - label: All validation actions (flake8, mypy, pytest) pass successfully
          required: true
        - label: Added or updated test cases for this feature (if applicable)
          required: false
        - label: Documentation updated (if applicable)
          required: false
