repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
            name: Remove trailing whitespace
          - id: end-of-file-fixer
            name: Ensure newline at end of file
          - id: check-yaml
            name: Check YAML syntax
          - id: check-added-large-files
            name: Prevent large files

    - repo: local
      hooks:
          - id: isort
            name: Sort Python imports (isort)
            entry: poetry run isort
            language: system
            args:
                ["--force-single-line", "--trailing-comma", "--use-parentheses"]
            types: [python]

          - id: autopep8
            name: Format Python code (autopep8)
            entry: poetry run autopep8
            language: system
            args: ["--in-place", "--aggressive", "--aggressive"]
            types: [python]

          - id: flake8
            name: Lint Python code (flake8)
            entry: poetry run flake8
            language: python
            additional_dependencies: [flake8, flake8-bugbear]
            types: [python]

          - id: mypy
            name: Type check (mypy)
            entry: poetry run mypy
            language: system
            types: [python]

          - id: pytest
            name: Run tests (pytest)
            entry: poetry run pytest
            language: system
            types: [python]
            pass_filenames: false
            always_run: true
            exclude: ""
