[project]
name = "pyportion"
version = "0.5.0"
description = "A Python CLI tool that helps developers kickstart new projects and manage existing ones"
authors = [
    {name = "Murtada",email = "murtada.altarouti@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gitpython (==3.1.45)",
    "platformdirs (==4.4.0)",
    "tabulate (==0.9.0)"
]

[tool.poetry]
packages = [
    { include = "portion" }
]

[tool.poetry.scripts]
portion = "portion.__main__:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pre-commit (>=4.3.0,<5.0.0)"
]
