name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the issue you encountered.
      placeholder: When I run `portion <command>` I expected X to happen, but Y happened instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide exact steps to reproduce the issue.
      placeholder: |
        1. Run `portion new` command
        2. Execute `portion add` command
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you expected PyPortion to do.
      placeholder: The command should have created a new module without errors.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happened instead.
      placeholder: "It threw an error: ModuleNotFoundError: ..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: PyPortion Version
      description: Which version of PyPortion are you using? (Check via `portion -v`)
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: The Python version you are using PyPortion with.
      placeholder: "e.g., 3.11"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: The OS you are running PyPortion on.
      placeholder: "e.g., Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm before submitting
      options:
        - label: I have checked for existing issues
          required: true
        - label: I have provided a clear description and steps to reproduce
          required: true
